[tool.poetry]
name = "auragen-ocr"
version = "1.0.0"
description = "AuraGen-OCR: Advanced document OCR, layout, reading order, and table recognition toolkit"
authors = ["Daniel Lopez <daniellopez882@users.noreply.github.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/daniellopez882/AuraGen-OCR"
keywords = ["ocr", "pdf", "text detection", "text recognition", "tables", "auragen"]
packages = [
    {include = "auragen"}
]

[tool.poetry.dependencies]
python = "^3.10"
transformers = ">=4.56.1"
torch = "^2.7.0"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
python-dotenv = "^1.0.0"
pillow = "^10.2.0"
pypdfium2 = "=4.30.0"
filetype = "^1.2.0"
click = "^8.1.8"
platformdirs = "^4.3.6"
opencv-python-headless = "==4.11.0.86"
einops = "^0.8.1"
pre-commit = "^4.2.0"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
pytesseract = "^0.3.10"
pymupdf = "^1.23.8"
datasets = "^2.16.1"
rapidfuzz = "^3.6.1"
streamlit = "^1.31.0"
pytest = "^8.3.4"
pdftext = "^0.5.1"
tabulate = "^0.9.0"

[tool.poetry.scripts]
auragen_detect = "auragen.scripts.detect_text:detect_text_cli"
auragen_ocr = "auragen.scripts.ocr_text:ocr_text_cli"
auragen_layout = "auragen.scripts.detect_layout:detect_layout_cli"
auragen_gui = "auragen.scripts.run_streamlit_app:streamlit_app_cli"
auragen_table = "auragen.scripts.table_recognition:table_recognition_cli"
auragen_latex_ocr = "auragen.scripts.ocr_latex:ocr_latex_cli"
texify_gui = "auragen.scripts.run_texify_app:texify_app_cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "libtpu-releases"
url = "https://storage.googleapis.com/libtpu-releases/index.html"
priority = "supplemental"

[[tool.poetry.source]]
name = "libtpu-wheels"
url = "https://storage.googleapis.com/libtpu-wheels/index.html"
priority = "supplemental"

[tool.poetry.group.xla]
optional = true

[tool.poetry.group.xla.dependencies]
torch-xla = {version = "^2.4.1", extras = ["tpu"]}
